name: nocterm
description: A Flutter-like framework for terminal UIs.
version: 0.1.0
repository: https://github.com/norbert515/nocterm
homepage: https://nocterm.dev
documentation: https://docs.page/Norbert515/nocterm~docs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansi_escape_codes: ^2.0.3
  characters: ^1.3.0
  crypto: ^3.0.3
  hotreloader: ^4.2.0
  markdown: ^7.2.0

  # TODO put this into a separate testing package
  matcher: ^0.12.17

  # XTerm dependencies
  convert: ^3.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
  equatable: ^2.0.3
  zmodem: ^0.0.6

dev_dependencies:
  test: ^1.25.6
  hooksman: ^3.1.1
