name: nocterm_provider
description: Provider integration for nocterm
version: 0.0.1
repository: https://github.com/norbert515/nocterm

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  nocterm: ^0.2.0
  nocterm_nested: ^0.0.1
