name: nocterm_cli
description: CLI tools for nocterm - TUI framework for Dart
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  nocterm: ^0.1.0
  scoped_deps: ^0.1.0+2
  meta: ^1.17.0
  file: ^7.0.1

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0

executables:
  nocterm: nocterm_cli.dart
